name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16, 18, 20]
        name: Use Node.js v${{ matrix.node-version }}
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm clean-install
            - name: Compile source code
              run: npm run compile
            - name: Run unit tests
              run: npm run test:unit:coverage
            - name: Check source code
              run: npm run lint
